---
title: "About"
---

## Brady Kennedy

My name is Brady Kennedy, and I am a researcher and data scientist with a background in econometrics and sociology.

[View my CV](cv.qmd)\
[View my portfolio](portfolio.qmd)

My main quantitative tools are R, SQL, and QGIS, but I am trained in Python and have more recently worked in qualitative and mixed-method research settings.

Before graduating with my MA in Sociology from Columbia, I honed my data analysis skills in multiple non-profit research positions and built my business and financial analysis in the private sector.

I am currently employed as a Researcher based within the Columbia University Department of Sociology. I am working on an interdisciplinary project aimed at identifying and quantifying the co-benefits of climate action in the housing sector.

My academic interests lie at the intersection of housing markets, climate action, and urban theory. My recent work has tended to be more applied in the city and state policy worlds focused on the rent-regulated housing market and building decarbonization.
